server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fresh_reach?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379

knife4j:
  basic:
    enable: false
  setting:
    language: zh_cn
springdoc:
  api-docs:
    enabled: true
    path: v3/api-docs
#    username: admin
#    password: admin
  swagger-ui:
    csrf:
      enabled: true
      path: /swagger-ui.html
#      username: admin
#      password: admin
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

